server:
    port: 4000

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: none

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/softwaredevelopercentral?autoReconnect=true&useSSL=false
        username: root
        password:
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 5